language: c
compiler:
  - gcc
  - clang
sudo: false
addons:
  apt:
    packages:
    - cmake                                   # CMake
    - libgtk-3-dev                            # GTK+ 3
install:
  - echo install
  - wget --output-document=remmina-plugin-builder.tar.gz
    https://github.com/muflone/remmina-plugin-builder/archive/1.4.27.0.tar.gz
  - tar --extract --verbose --gzip --file remmina-plugin-builder.tar.gz
  - cp --verbose --recursive remmina-plugin-rustdesk CMakeLists.txt
    remmina-plugin-builder-1.4.27.0/remmina-plugin-to-build/
script:
  - echo script
  - cd remmina-plugin-builder-1.4.27.0
  - cmake .
    -DCMAKE_INSTALL_PREFIX=install_dir
    -DWITH_TRACE_CALLS=ON
  - make
  - make install
