version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            sudo apt update
            # Dependencies for installation
            sudo apt install cmake libgtk-3-dev
      - run:
          name: build
          command: |
            wget --output-document=remmina-plugin-builder.tar.gz \
              https://github.com/muflone/remmina-plugin-builder/archive/1.4.27.0.tar.gz
            tar --extract --verbose --gzip --file remmina-plugin-builder.tar.gz
            cp --verbose --recursive remmina-plugin-rustdesk CMakeLists.txt \
              remmina-plugin-builder-1.4.27.0/remmina-plugin-to-build
            cd remmina-plugin-builder-1.4.27.0
            cmake . -DCMAKE_INSTALL_PREFIX=install_dir -DWITH_TRACE_CALLS=ON
            make
            make install
